# Generated by Django 3.2.16 on 2024-07-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name_ko', models.CharField(max_length=255)),
                ('course_name_en', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=50)),
                ('level', models.CharField(default='1학년', max_length=20)),
                ('credits', models.CharField(max_length=10)),
                ('pf', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('summary', models.TextField(default='Course summary goes here.')),
                ('average_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(default='No comment')),
                ('homework', models.CharField(default='N/A', max_length=10)),
                ('groupwork', models.CharField(default='N/A', max_length=10)),
                ('grading', models.CharField(default='N/A', max_length=10)),
                ('attendance', models.CharField(default='N/A', max_length=20)),
                ('exams', models.CharField(default='N/A', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
            ],
        ),
    ]
