# Generated by Django 3.2.16 on 2024-08-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='attendance',
            field=models.CharField(choices=[('complex', '복합적'), ('direct', '직접호명'), ('designated', '지정좌석'), ('electronic', '전자출결'), ('none', '반영안함')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='exams',
            field=models.CharField(choices=[('4_or_more', '네 번 이상'), ('3', '세 번'), ('2', '두 번'), ('1', '한 번'), ('none', '없음')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='grading',
            field=models.CharField(choices=[('generous', '너그러움'), ('average', '보통'), ('strict', '깐깐함')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='groupwork',
            field=models.CharField(choices=[('many', '많음'), ('average', '보통'), ('none', '없음')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='homework',
            field=models.CharField(choices=[('many', '많음'), ('average', '보통'), ('none', '없음')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lecture.lecture'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
