# Generated by Django 3.2.16 on 2024-07-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20240717_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course_type',
        ),
        migrations.AddField(
            model_name='review',
            name='attendance',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='exams',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='grading',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='groupwork',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='homework',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='schedule',
            field=models.CharField(max_length=255),
        ),
    ]
