# Generated by Django 3.2.16 on 2024-07-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_alter_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='section',
        ),
        migrations.AddField(
            model_name='lecture',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='grading',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='groupwork',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='homework',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture'),
        ),
    ]
