# Generated by Django 3.2.16 on 2024-07-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techtime', '0003_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='grade_level',
            new_name='course_level',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name_kr',
            new_name='course_name_ko',
        ),
        migrations.AlterField(
            model_name='course',
            name='pf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
