# Generated by Django 3.2.16 on 2024-07-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='000-0000-0000', max_length=15),
        ),
    ]
