# Generated by Django 3.2.16 on 2024-07-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_anonymous',
            new_name='anonymous_status',
        ),
    ]
