# Generated by Django 3.2.16 on 2024-07-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_is_anonymous_user_anonymous_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='anonymous_status',
            new_name='is_anonymous',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
