# Generated by Django 3.2.16 on 2024-07-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_articlecomment_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
